# This file is generated by nvimx. Do not edit by hand.
{
  inputs = {
    lazy-nvim = {
      url = "github:folke/lazy.nvim";
      flake = false;
    };
    branchy-nvim = {
      url = "github:o/branchy.nvim/trunk";
      flake = false;
    };
    committed-nvim = {
      url = "github:o/committed.nvim/1111111111111111111111111111111111111111";
      flake = false;
    };
    deps-nvim = {
      url = "github:o/deps.nvim";
      flake = false;
    };
    excmdbuild-nvim = {
      url = "github:o/excmdbuild.nvim";
      flake = false;
    };
    gittag-nvim = {
      url = "git+https://git.example.com/o/gittag.nvim.git?ref=refs/tags/v2.0.0";
      flake = false;
    };
    plain-nvim = {
      url = "github:o/plain.nvim";
      flake = false;
    };
    shellbuild-nvim = {
      url = "github:o/shellbuild.nvim";
      flake = false;
    };
    tagged-nvim = {
      url = "github:o/tagged.nvim/refs/tags/v1.0.0";
      flake = false;
    };
    versioned-nvim = {
      url = "git+file:///nvimx-fixture/versioned.nvim?ref=refs/tags/v1.2.5";
      flake = false;
    };
  };
  outputs = _: { };
}
