# This file is generated by nvimx. Do not edit by hand.
{
  inputs = {
    lazy-nvim = {
      url = "github:folke/lazy.nvim";
      flake = false;
    };
    gh-branch-nvim = {
      url = "github:o/gh-branch.nvim/b";
      flake = false;
    };
    gh-commit-nvim = {
      url = "github:o/gh-commit.nvim/1111111111111111111111111111111111111111";
      flake = false;
    };
    gh-plain-nvim = {
      url = "github:o/gh-plain.nvim";
      flake = false;
    };
    gh-resolved-nvim = {
      url = "github:o/gh-resolved.nvim/2222222222222222222222222222222222222222";
      flake = false;
    };
    gh-tag-nvim = {
      url = "github:o/gh-tag.nvim/refs/tags/v9.9.9";
      flake = false;
    };
    git-branch-nvim = {
      url = "git+https://git.example.com/o/git-branch.nvim.git?ref=b";
      flake = false;
    };
    git-commit-nvim = {
      url = "git+https://git.example.com/o/git-commit.nvim.git?ref=b&rev=3333333333333333333333333333333333333333";
      flake = false;
    };
    git-frozen-nvim = {
      url = "git+https://git.example.com/o/git-frozen.nvim.git?ref=refs/tags/v9.9.9&rev=4444444444444444444444444444444444444444";
      flake = false;
    };
    git-plain-nvim = {
      url = "git+https://git.example.com/o/git-plain.nvim.git";
      flake = false;
    };
    git-symbolic-nvim = {
      url = "git+https://git.example.com/o/git-symbolic.nvim.git?ref=refs/tags/v1.2.3";
      flake = false;
    };
    git-tag-nvim = {
      url = "git+https://git.example.com/o/git-tag.nvim.git?ref=refs/tags/v9.9.9";
      flake = false;
    };
  };
  outputs = _: { };
}
