# This file is generated by nvimx. Do not edit by hand.
{
  inputs = {
    lazy-nvim = {
      url = "github:folke/lazy.nvim";
      flake = false;
    };
    file-nvim = {
      url = "git+file:///nvimx-nonexistent/file.nvim";
      flake = false;
    };
    ghe-nvim = {
      url = "git+https://github.example.com/o/ghe.nvim.git";
      flake = false;
    };
    ghtag-nvim = {
      url = "github:o/ghtag.nvim/refs/tags/v1.0.0";
      flake = false;
    };
    gitproto-nvim = {
      url = "git+git://git.example.com/o/gitproto.nvim.git";
      flake = false;
    };
    http-nvim = {
      url = "git+http://git.example.com/o/http.nvim.git";
      flake = false;
    };
    httpgh-nvim = {
      url = "git+http://github.com/o/httpgh.nvim.git";
      flake = false;
    };
    nested-nvim = {
      url = "git+https://gitlab.com/g/sub/nested.nvim.git";
      flake = false;
    };
    nodotgit-nvim = {
      url = "github:o/nodotgit.nvim";
      flake = false;
    };
    scp-nvim = {
      url = "git+ssh://git@git.example.com/o/scp.nvim.git";
      flake = false;
    };
    scpbranch-nvim = {
      url = "git+ssh://git@git.example.com/o/scpbranch.nvim.git?ref=trunk";
      flake = false;
    };
    scpcommit-nvim = {
      url = "git+ssh://git@git.example.com/o/scpcommit.nvim.git?rev=cccccccccccccccccccccccccccccccccccccccc";
      flake = false;
    };
    scpgh-nvim = {
      url = "git+ssh://git@github.com/o/scpgh.nvim.git";
      flake = false;
    };
    scpuser-nvim = {
      url = "git+ssh://forgejo@git.example.com/o/scpuser.nvim.git";
      flake = false;
    };
    short-nvim = {
      url = "github:o/short.nvim";
      flake = false;
    };
    single-nvim = {
      url = "git+https://git.example.com/single.nvim.git";
      flake = false;
    };
    ssh-nvim = {
      url = "git+ssh://git@git.example.com/o/ssh.nvim.git";
      flake = false;
    };
    sshport-nvim = {
      url = "git+ssh://git@git.example.com:2222/o/sshport.nvim.git";
      flake = false;
    };
    tildeuser-nvim = {
      url = "git+https://git.sr.ht/~user/tildeuser.nvim";
      flake = false;
    };
    trailing-nvim = {
      url = "github:o/trailing.nvim/";
      flake = false;
    };
    upperhost-nvim = {
      url = "git+https://GitHub.com/o/upperhost.nvim";
      flake = false;
    };
  };
  outputs = _: { };
}
