# programs.nvimx: the home-manager module.
# It embeds lib.makeEnv and deploys the wrapped neovim + nvimx-lock from a single place.
# lazyNvimSeed is nvimx's flake input (partially applied in flake.nix).
{ lazyNvimSeed }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.nvimx;
  nvimxLib = import ../lib { inherit pkgs lazyNvimSeed; };

  # When projectDir is set, wrap the command so that running it without arguments has defaults
  lockCommand =
    if cfg.lock.projectDir == null then
      nvimxLib.lockApp
    else
      pkgs.writeShellScriptBin "nvimx-lock" ''
        if [ "$#" -eq 0 ]; then
          project=${lib.escapeShellArg cfg.lock.projectDir}
          project=''${project/#\~/$HOME}
          exec ${nvimxLib.lockApp}/bin/nvimx-lock \
            --config "$project/"${lib.escapeShellArg cfg.lock.configDirRelative} \
            --out "$project/"${lib.escapeShellArg cfg.lock.lockDirRelative}
        fi
        exec ${nvimxLib.lockApp}/bin/nvimx-lock "$@"
      '';
in
{
  options.programs.nvimx = {
    enable = lib.mkEnableOption "nvimx (nix x neovim manager)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.neovim-unwrapped;
      defaultText = lib.literalExpression "pkgs.neovim-unwrapped";
      description = ''
        neovim itself (an -unwrapped style derivation).
        A package from neovim-nightly-overlay works here too.
      '';
    };

    configDir = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = lib.literalExpression "./nvim";
      description = ''
        The lua config directory containing init.lua.
        When manageConfig = true it is deployed from the store via xdg.configFile.
      '';
    };

    lockDir = lib.mkOption {
      type = lib.types.path;
      example = lib.literalExpression "./nvim/nvimx-lock";
      description = ''
        Where the plugins.json / flake.nix / flake.lock generated by nvimx-lock live.
        If they have not been generated yet (no lock), the build degrades.
      '';
    };

    manageConfig = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        true: deploy configDir from the store via xdg.configFile (reproducibility-first, the default).
        false: ~/.config/nvim stays user-managed (for fast iteration).
      '';
    };

    vimAlias = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Add a symlink so that the `vim` command launches the wrapped neovim";
    };

    viAlias = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Add a symlink so that the `vi` command launches the wrapped neovim";
    };

    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = lib.literalExpression "[ pkgs.ripgrep pkgs.lua-language-server ]";
      description = "Packages prepended to the wrapper's PATH (ripgrep, lsp servers, etc.)";
    };

    lock = {
      installCommand = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Add the nvimx-lock command to home.packages";
      };

      projectDir = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "~/dotfiles";
        description = ''
          The working tree of your dotfiles repository. When set, running
          `nvimx-lock` without arguments targets configDirRelative / lockDirRelative.
        '';
      };

      configDirRelative = lib.mkOption {
        type = lib.types.str;
        default = "nvim";
        description = "Path to configDir, relative to projectDir";
      };

      lockDirRelative = lib.mkOption {
        type = lib.types.str;
        default = "nvim/nvimx-lock";
        description = "Path to lockDir, relative to projectDir";
      };
    };

    env = lib.mkOption {
      type = lib.types.attrs;
      defaultText = lib.literalExpression "nvimx lib.makeEnv { ... }";
      description = ''
        The result of makeEnv (farm / bootstrap / wrapped / hasLock).
        By default it is built automatically from the options above.
        This is an escape hatch for advanced users who want to supply it directly.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.manageConfig -> cfg.configDir != null;
        message = "programs.nvimx: manageConfig = true requires configDir to be set";
      }
    ];

    warnings = lib.optional (!(cfg.env.hasLock or true)) ''
      programs.nvimx: lock files (plugins.json / flake.lock) not found in lockDir.
      Building in degraded mode (lazy.nvim seed only).
      Run `nvimx-lock`, commit the lock files, then re-run home-manager switch.
    '';

    programs.nvimx.env = lib.mkDefault (
      nvimxLib.makeEnv {
        inherit (cfg)
          package
          lockDir
          extraPackages
          vimAlias
          viAlias
          ;
      }
    );

    home.packages = [ cfg.env.wrapped ] ++ lib.optional cfg.lock.installCommand lockCommand;

    xdg.configFile = lib.mkIf cfg.manageConfig {
      nvim.source = cfg.configDir;
    };

    # Make the fs_stat in the standard bootstrap snippet succeed, neutralizing its git clone
    xdg.dataFile."nvim/lazy/lazy.nvim".source = "${cfg.env.farm}/lazy.nvim";
  };
}
