# programs.nvimx: the home-manager module.
# It embeds lib.makeEnv and deploys the wrapped neovim + nvimx-lock from a single place.
# lazyNvimSeed is nvimx's flake input (partially applied in flake.nix).
{ lazyNvimSeed }:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.nvimx;
  nvimxLib = import ../lib { inherit pkgs lazyNvimSeed; };

  # When projectDir is set, wrap the command so that running it without arguments has defaults
  lockCommand =
    if cfg.lock.projectDir == null then
      nvimxLib.lockApp
    else
      pkgs.writeShellScriptBin "nvimx-lock" ''
        if [ "$#" -eq 0 ]; then
          project=${lib.escapeShellArg cfg.lock.projectDir}
          project=''${project/#\~/$HOME}
          exec ${nvimxLib.lockApp}/bin/nvimx-lock \
            --config "$project/"${lib.escapeShellArg cfg.lock.configDirRelative} \
            --out "$project/"${lib.escapeShellArg cfg.lock.lockDirRelative}
        fi
        exec ${nvimxLib.lockApp}/bin/nvimx-lock "$@"
      '';
in
{
  options.programs.nvimx = {
    enable = lib.mkEnableOption "nvimx (nix x neovim manager)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.neovim-unwrapped;
      defaultText = lib.literalExpression "pkgs.neovim-unwrapped";
      description = ''
        neovim itself (an -unwrapped style derivation).
        A package from neovim-nightly-overlay works here too.
      '';
    };

    configDir = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = lib.literalExpression "./nvim";
      description = ''
        The lua config directory containing init.lua.
        When manageConfig = true it is deployed from the store via xdg.configFile.
      '';
    };

    lockDir = lib.mkOption {
      type = lib.types.path;
      example = lib.literalExpression "./nvim/nvimx-lock";
      description = ''
        Where the plugins.json / flake.nix / flake.lock generated by nvimx-lock live.
        If they have not been generated yet (no lock), the build degrades.
      '';
    };

    manageConfig = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        true: deploy configDir from the store via xdg.configFile (reproducibility-first, the default).
        false: ~/.config/nvim stays user-managed (for fast iteration).
      '';
    };

    vimAlias = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Add a symlink so that the `vim` command launches the wrapped neovim";
    };

    viAlias = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Add a symlink so that the `vi` command launches the wrapped neovim";
    };

    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = lib.literalExpression "[ pkgs.ripgrep pkgs.lua-language-server ]";
      description = "Packages prepended to the wrapper's PATH (ripgrep, lsp servers, etc.)";
    };

    plugins = {
      overrides = lib.mkOption {
        type = lib.types.attrsOf (lib.types.functionTo lib.types.package);
        default = { };
        example = lib.literalExpression ''
          {
            "markdown-preview.nvim" =
              { pkgs, defaultDrv, ... }:
              defaultDrv.overrideAttrs (o: {
                nativeBuildInputs = o.nativeBuildInputs ++ [ pkgs.nodejs ];
              });
          }
        '';
        description = ''
          Per-plugin derivation overrides, keyed by the plugin name lazy derived.
          The function receives { pkgs, name, src, build, defaultDrv, mkPluginDrv } and must
          return a derivation. Always accept `...` as well: more arguments may be added later.

          `src` is the locked source tree and `defaultDrv` is the derivation nvimx would
          have used without this override, so both patching (defaultDrv.overrideAttrs)
          and replacing it outright (build your own from src) work. `mkPluginDrv` is nvimx's
          generic builder ({ name, src, build } -> drv), for "the usual treatment, but with
          the build command corrected" -- which is also how to bypass a nix/build-registry
          recipe nvimx ships for the plugin.

          This wins over every other resolution step, and it is the way out when a plugin's
          build cannot run inside the nix sandbox.
        '';
      };

      nixpkgsFallback = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [ "telescope-fzf-native.nvim" ];
        description = ''
          Plugin names to take from pkgs.vimPlugins as-is instead of building from the lock.
          Opt-in per plugin: matching names automatically would silently detach plugins from
          their flake.lock pins.

          The nixpkgs attribute is looked up by the name verbatim (LazyVim), then with "."
          replaced by "-" (CopilotChat.nvim -> CopilotChat-nvim), then lowercased on top of
          that (telescope.nvim -> telescope-nvim). A name that resolves to none of the three
          fails evaluation; use plugins.overrides to point at an attribute directly.
        '';
      };
    };

    lock = {
      installCommand = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Add the nvimx-lock command to home.packages";
      };

      projectDir = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "~/dotfiles";
        description = ''
          The working tree of your dotfiles repository. When set, running
          `nvimx-lock` without arguments targets configDirRelative / lockDirRelative.
        '';
      };

      configDirRelative = lib.mkOption {
        type = lib.types.str;
        default = "nvim";
        description = "Path to configDir, relative to projectDir";
      };

      lockDirRelative = lib.mkOption {
        type = lib.types.str;
        default = "nvim/nvimx-lock";
        description = "Path to lockDir, relative to projectDir";
      };
    };

    env = lib.mkOption {
      type = lib.types.attrs;
      defaultText = lib.literalExpression "nvimx lib.makeEnv { ... }";
      description = ''
        The result of makeEnv (farm / bootstrap / wrapped / pluginDrvs /
        unknownPluginNames / hasLock).
        By default it is built automatically from the options above.
        This is an escape hatch for advanced users who want to supply it directly.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.manageConfig -> cfg.configDir != null;
        message = "programs.nvimx: manageConfig = true requires configDir to be set";
      }
    ];

    warnings =
      lib.optional (!(cfg.env.hasLock or true)) ''
        programs.nvimx: lock files (plugins.json / flake.lock) not found in lockDir.
        Building in degraded mode (lazy.nvim seed only).
        Run `nvimx-lock`, commit the lock files, then re-run home-manager switch.
      ''
      ++ lib.optional ((cfg.env.unknownPluginNames or [ ]) != [ ]) ''
        programs.nvimx: plugins.overrides / plugins.nixpkgsFallback name plugins that are
        not in the lock, so they have no effect:
        ${lib.concatMapStringsSep "\n" (n: "  - ${n}") (cfg.env.unknownPluginNames or [ ])}
        Use the name lazy derived for the plugin (the key in nvimx-lock/plugins.json).
      '';

    programs.nvimx.env = lib.mkDefault (
      nvimxLib.makeEnv {
        inherit (cfg)
          package
          lockDir
          extraPackages
          vimAlias
          viAlias
          plugins
          ;
      }
    );

    home.packages = [ cfg.env.wrapped ] ++ lib.optional cfg.lock.installCommand lockCommand;

    xdg.configFile = lib.mkIf cfg.manageConfig {
      nvim.source = cfg.configDir;
    };

    # Make the fs_stat in the standard bootstrap snippet succeed, neutralizing its git clone
    xdg.dataFile."nvim/lazy/lazy.nvim".source = "${cfg.env.farm}/lazy.nvim";
  };
}
