-- nvimx lock flake generator (minimal Phase 2 version)
--
-- Usage: nvim -l genflake.lua <plugins.json> <where to write flake.nix>
--
-- Generates the flake.nix for lockDir from plugins.json.
-- This flake is never evaluated as a flake; it exists only to produce a flake.lock
-- that serves as a pin DB (its outputs are empty).

local plugins_path, out_path = arg[1], arg[2]
assert(plugins_path and out_path, "usage: nvim -l genflake.lua <plugins.json> <flake.nix>")

local function read_json(path)
  local f = assert(io.open(path, "r"))
  local text = f:read("*a")
  f:close()
  return vim.json.decode(text)
end

local db = read_json(plugins_path)

local function is_null(v)
  return v == nil or v == vim.NIL
end

-- lazy spec → flake input URL mapping (see docs/architecture.md)
local function input_url(p)
  local src = p.source
  if src.type == "github" then
    local base = ("github:%s/%s"):format(src.owner, src.repo)
    if not is_null(p.commit) then
      return base .. "/" .. p.commit
    elseif not is_null(p.resolvedRef) then
      return base .. "/" .. p.resolvedRef
    elseif not is_null(p.tag) then
      return base .. "/refs/tags/" .. p.tag
    elseif not is_null(p.branch) then
      return base .. "/" .. p.branch
    end
    return base
  end
  -- explicit git URL
  local url = "git+" .. src.url
  local ref = (not is_null(p.branch) and p.branch) or (not is_null(p.tag) and p.tag) or nil
  if ref then
    url = url .. "?ref=" .. ref
  end
  return url
end

local inputs = {}
inputs[#inputs + 1] = { name = db.lazyNvim.inputName, url = input_url({ source = db.lazyNvim.source }) }
local names = vim.tbl_keys(db.plugins or {})
table.sort(names)
for _, name in ipairs(names) do
  local p = db.plugins[name]
  inputs[#inputs + 1] = { name = p.inputName, url = input_url(p) }
end

local lines = {
  "# This file is generated by nvimx. Do not edit by hand.",
  "{",
  "  inputs = {",
}
for _, i in ipairs(inputs) do
  lines[#lines + 1] = ("    %s = {"):format(i.name)
  lines[#lines + 1] = ("      url = %q;"):format(i.url)
  lines[#lines + 1] = "      flake = false;"
  lines[#lines + 1] = "    };"
end
lines[#lines + 1] = "  };"
lines[#lines + 1] = "  outputs = _: { };"
lines[#lines + 1] = "}"

local f = assert(io.open(out_path, "w"))
f:write(table.concat(lines, "\n"))
f:write("\n")
f:close()
