-- nvimx lock flake generator (minimal Phase 2 version)
--
-- Usage: nvim -l genflake.lua <plugins.json> <where to write flake.nix>
--
-- Generates the flake.nix for lockDir from plugins.json.
-- This flake is never evaluated as a flake; it exists only to produce a flake.lock
-- that serves as a pin DB (its outputs are empty).

local plugins_path, out_path = arg[1], arg[2]
assert(plugins_path and out_path, "usage: nvim -l genflake.lua <plugins.json> <flake.nix>")

local function read_json(path)
  local f = assert(io.open(path, "r"))
  local text = f:read("*a")
  f:close()
  return vim.json.decode(text)
end

local db = read_json(plugins_path)

local function is_null(v)
  return v == nil or v == vim.NIL
end

-- lazy spec → flake input URL mapping (see docs/architecture.md). owner/repo never containing an
-- interior "/" -- a lone trailing "/" on repo survives, kept for the plan's §3.4 compatibility
-- invariant -- or a "?", and src.url never carrying a query string or "${", is guaranteed by
-- lua/nvimx/source.lua (#28) -- this file trusts that and does no validation of its own. The "${"
-- guarantee matters here specifically: every src.owner / src.repo / src.url is written below with
-- Lua's %q, which does not escape "${", so one slipping through would land in the generated
-- flake.nix as a live Nix string interpolation and die with an "undefined variable" error that
-- names neither this plugin nor its URL.
local function input_url(p)
  local src = p.source
  if src.type == "github" then
    local base = ("github:%s/%s"):format(src.owner, src.repo)
    if not is_null(p.commit) then
      return base .. "/" .. p.commit
    elseif not is_null(p.resolvedRef) then
      return base .. "/" .. p.resolvedRef
    elseif not is_null(p.tag) then
      return base .. "/refs/tags/" .. p.tag
    elseif not is_null(p.branch) then
      return base .. "/" .. p.branch
    end
    return base
  end
  -- explicit git URL. Unlike the github type, ref and rev are separate query parameters rather
  -- than one path component, so a pinned rev can be carried alongside the branch it lives on.
  local url = "git+" .. src.url
  local rev, ref
  if not is_null(p.commit) then
    rev = p.commit
  elseif not is_null(p.resolvedRef) then
    -- resolvedRef is either a frozen 40-hex rev (pin) or a symbolic ref such as refs/tags/v1.2.3
    if p.resolvedRef:match("^%x+$") and #p.resolvedRef == 40 then
      rev = p.resolvedRef
    else
      ref = p.resolvedRef
    end
  end
  -- A tag has to be spelled out in full: nix expands a `ref` with no "refs/" prefix to
  -- refs/heads/<ref>, so the short tag name would be looked for among the branches.
  ref = ref or (not is_null(p.tag) and ("refs/tags/" .. p.tag)) or (not is_null(p.branch) and p.branch) or nil
  local params = {}
  if ref then
    params[#params + 1] = "ref=" .. ref
  end
  if rev then
    params[#params + 1] = "rev=" .. rev
  end
  if #params > 0 then
    url = url .. "?" .. table.concat(params, "&")
  end
  return url
end

local inputs = {}
inputs[#inputs + 1] = { name = db.lazyNvim.inputName, url = input_url({ source = db.lazyNvim.source }) }
local names = vim.tbl_keys(db.plugins or {})
table.sort(names)
for _, name in ipairs(names) do
  local p = db.plugins[name]
  inputs[#inputs + 1] = { name = p.inputName, url = input_url(p) }
end

local lines = {
  "# This file is generated by nvimx. Do not edit by hand.",
  "{",
  "  inputs = {",
}
for _, i in ipairs(inputs) do
  lines[#lines + 1] = ("    %s = {"):format(i.name)
  lines[#lines + 1] = ("      url = %q;"):format(i.url)
  lines[#lines + 1] = "      flake = false;"
  lines[#lines + 1] = "    };"
end
lines[#lines + 1] = "  };"
lines[#lines + 1] = "  outputs = _: { };"
lines[#lines + 1] = "}"

local f = assert(io.open(out_path, "w"))
f:write(table.concat(lines, "\n"))
f:write("\n")
f:close()
