name: check

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

jobs:
  check:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - name: Run flake checks
        run: nix flake check

      - name: Check formatting
        run: nix fmt -- --ci
